### PR TITLE
Dereference optional values.

### LINKED ISSUE #22: Array of structs doesn't work
I thought this should work, but it doesn't...

```ruby
require 'dry-data'

module Types
end

Dry::Data.configure do |config|
  config.namespace = Types
end

Dry::Data.finalize

class Book < Dry::Data::Value
  attribute :name,      Types::Maybe::Strict::String
end

class Shelf < Dry::Data::Value
  attribute :books,     Types::Strict::Array.member(Book)
end

book1 = Book.new(:name => 'A book name')
book2 = Book.new(:name => 'Another book')

puts Shelf.new(:books => [book1, book2]).inspect
```

```
Dry::Data::StructError: [Shelf.new] [#<Book name=Some("A book name")>, #<Book name=Some("Another book")>] (Array) has invalid type for :books
        from /usr/lib/ruby/gems/2.3.0/gems/dry-data-0.5.1/lib/dry/data/struct.rb:36:in `rescue in new'
        from /usr/lib/ruby/gems/2.3.0/gems/dry-data-0.5.1/lib/dry/data/struct.rb:34:in `new'
```

### PR DESCRIPTION
**Pull request by marshall-lee**
Fixes #22.

### CODE REVIEW

**Comment by marshall-lee** [comment]
I wonder is it a way to go or not?

**Comment by solnic** [comment]
I'm not sure to be honest. I'll investigate this later next week.

**Comment by marshall-lee** [comment]
@solnic Anyway, don't you think that `Some("SomeString")` should typecheck with `Types::Maybe::Strict::String`?

**Comment by marshall-lee** [comment]
Now I'm not sure too. Constructor should not be called on objects constructed by itself (if it's not a recursive data type, of course).

**Comment by solnic** [comment]
I'll be refining behavior of `Type` objects a bit for the next release, so *maybe* this issue will go away as a side-effect of this refactoring. At least that's what I'm hoping for hah!

**Pull request closed without merging**
